### PR TITLE
Completed css-canvas-medical Exercise. -Anna Park

### PR DESCRIPTION
**Pull request by annuhpark**
https://user-images.githubusercontent.com/69396309/151918593-4d6b3b38-c26b-4516-8c95-202e4ca839f6.mov

### CODE REVIEW

**Review by codingcodymiller — CHANGES_REQUESTED** [review]
Hey Anna! You are missing an overlay on the hero image, the image in the output is a bit more faded than the image itself. I suggest looking back at the `absolute` portion of `css-positioning` for a reminder of how to do an overlay effectively.

**Comment by annuhpark** [comment]
https://user-images.githubusercontent.com/69396309/152590627-abf4c241-d481-4614-8ac1-5c768c409754.mov

**Review by codingcodymiller — CHANGES_REQUESTED** [review]
Hey Anna! I see that you have a `row` class and a `container` class, but you are not properly making use of `column` classes to size out elements inside your rows. Please review `css-layout-classes` and revise this to make proper use of `column` classes.

**Review by codingcodymiller — APPROVED** [review]
Nice work!

**Pull request merged**
